apiVersion: v1
kind: ServiceAccount
metadata:
  name: prober
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prober
spec:
  replicas: 1
  template:
    spec:
      serviceAccountName: prober
      restartPolicy: Always
      containers:
        - name: main
          image: nicolaka/netshoot
          command: ["/entrypoint.sh"]
          env:
          - name: SERVICE_TO_CURL
            value: echo.echo.svc.cluster.local
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 100m
              memory: 100Mi
          volumeMounts:
            - name: prober-entrypoint
              mountPath: /entrypoint.sh
              subPath: entrypoint.sh
      volumes:
        - name: prober-entrypoint
          configMap:
            name: prober-entrypoint
            defaultMode: 0777
