---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: echo-istio-ingress

resources:
  - ./ns.yaml
  - ./svc.yaml
  - ./echo_v1.yaml
  - ./echo_v2.yaml
  - ./vs-gw.yaml
  - ./gw.yaml
  - ./dr.yaml
