---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: echo

resources:
  - ./ns.yaml
  - ./svc.yaml
  - ./echo_v1.yaml
  - ./echo_v2.yaml
  - ./vs.yaml
  - ./dr.yaml
  - ./ap.yaml
  - ./peer-auth.yaml
